<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="PB_TestRunner" Id="{63470fcc-b57d-026d-334d-1963f895812d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PB_TestRunner
VAR
    
    Test_FormatStringWith4CharHexValue                     : Test_FormatStringWith4CharHexValue;
    Test_FormatStringWith8CharHexValue                     : Test_FormatStringWith8CharHexValue;
                                                            
    Test_F_DateAsString_ReturnsDateString                  : Test_F_DateAsString_ReturnsDateString;
    Test_F_DateTimeAsString_ReturnsDateTimeString          : Test_F_DateTimeAsString_ReturnsDateTimeString;
    Test_F_DateTimeAsString_ms_ReturnsDateTimeString       : Test_F_DateTimeAsString_ms_ReturnsDateTimeString;
    Test_F_TimeAsString_ReturnsTimeString_24HourFormat     : Test_F_TimeAsString_ReturnsTimeString_24HourFormat;
    Test_F_TimeAsString_ReturnsTimeStringWithLeadingZeros  : Test_F_TimeAsString_ReturnsTimeStringWithLeadingZeros;
    Test_F_TimeAsString_ms_ReturnsTimeString_ms            : Test_F_TimeAsString_ms_ReturnsTimeString_ms;
    Test_F_TimestampAsFilenameString_ReturnsFilenameString : Test_F_TimestampAsFilenameString_ReturnsFilenameString;
                                                            
    Test_TStringSplitter_Handles_Empty_String              : Test_TStringSplitter_Handles_Empty_String;
    Test_TStringSplitter_ReturnsRemainder                  : Test_TStringSplitter_ReturnsRemainder;
    Test_TStringSplitter_Splits_On_Tab                     : Test_TStringSplitter_Splits_On_Tab;
                                                            
    Test_F_PadString_PadsShortStrings                      : Test_F_PadString_PadsShortStrings;
    Test_F_PadString_TruncsLongString                      : Test_F_PadString_TruncsLongStrings;


END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[tcl_SimpleUnitTestLibrary.TestFramework.TestRunner(RunTestsSequentially := TRUE);


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>