<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="T_TestSuite" Id="{ed36e071-030c-06b0-182e-924def1f2a1d}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK T_TestSuite
VAR
    Test_StringToIpAddress                                 : Test_StringToIpAddress;
    Test_FormatStringWith4CharHexValue                     : Test_FormatStringWith4CharHexValue;
    Test_FormatStringWith8CharHexValue                     : Test_FormatStringWith8CharHexValue;
    Test_LTrimEx_HandlesEmptySubject                       : Test_LTrimEx_HandlesEmptySubject;
    Test_LTrimEx_HandlesTrimmingNoChars                    : Test_LTrimEx_HandlesTrimmingNoChars;
    Test_LTrimEx_HandlesTrimmingManyChars                  : Test_LTrimEx_HandlesTrimmingManyChars;
    Test_RTrimEx_HandlesEmptySubject                       : Test_RTrimEx_HandlesEmptySubject;
    Test_RTrimEx_HandlesTrimmingNoChars                    : Test_RTrimEx_HandlesTrimmingNoChars;
    Test_RTrimEx_HandlesTrimmingManyChars                  : Test_RTrimEx_HandlesTrimmingManyChars;
    Test_TrimEx_HandlesTrimmingOnlyWhitespace              : Test_TrimEx_HandlesTrimmingOnlyWhitespace;
    Test_TrimEx_HandlesEmptySubject                        : Test_TrimEx_HandlesEmptySubject;
    Test_F_DateAsString_ReturnsDateString                  : Test_F_DateAsString_ReturnsDateString;
    Test_F_DateTimeAsString_ReturnsDateTimeString          : Test_F_DateTimeAsString;
    Test_F_DateTimeAsString_ms_ReturnsDTStr                : Test_F_DateTimeAsString_ms;
    Test_F_TimeAsString_Returns24HourFormat                : Test_F_TimeAsString_Returns24HourFormat;
    Test_F_TimeAsString_ReturnsLeadingZeros                : Test_F_TimeAsString_ReturnsLeadingZeros;
    Test_F_TimeAsString_ms_ReturnsTimeString_ms            : Test_F_TimeAsString_ms_ReturnsString_ms;
    Test_F_TimestampAsFilenameString_ReturnsFilenameString : Test_F_TimestampAsFilename_ReturnsValue;
    Test_TStringSplitter_Handles_Empty_String              : Test_TStringSplitter_Handles_Empty_String;
    Test_TStringSplitter_ReturnsRemainder                  : Test_TStringSplitter_ReturnsRemainder;
    Test_TStringSplitter_Splits_On_Tab                     : Test_TStringSplitter_Splits_On_Tab;
    Test_TStringSplitter_Handles_Empty_SubString           : Test_TStringSplitter_Handles_Empty_SubString;
    Test_TStringSplitter_Handles_Multiple_Empty_SubStrings : Test_TStringSplitter_Handles_Multiple_Empty;
    Test_F_PadString_PadsShortStrings                      : Test_F_PadString_PadsShortStrings;
    Test_F_PadString_TruncsLongString                      : Test_F_PadString_TruncsLongStrings;
    Test_F_TimestampAsFilename_ms                          : Test_F_TimestampAsFilename_ms;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Test_StringToIpAddress.RunTest();
Test_FormatStringWith4CharHexValue.RunTest();
Test_FormatStringWith8CharHexValue.RunTest();
Test_LTrimEx_HandlesEmptySubject.RunTest();
Test_LTrimEx_HandlesTrimmingNoChars.RunTest();
Test_LTrimEx_HandlesTrimmingManyChars.RunTest();
Test_RTrimEx_HandlesEmptySubject.RunTest();
Test_RTrimEx_HandlesTrimmingNoChars.RunTest();
Test_RTrimEx_HandlesTrimmingManyChars.RunTest();
Test_TrimEx_HandlesTrimmingOnlyWhitespace.RunTest();
Test_TrimEx_HandlesEmptySubject.RunTest();
Test_F_DateAsString_ReturnsDateString.RunTest();
Test_F_DateTimeAsString_ReturnsDateTimeString.RunTest();
Test_F_DateTimeAsString_ms_ReturnsDTStr.RunTest();
Test_F_TimeAsString_Returns24HourFormat.RunTest();
Test_F_TimeAsString_ReturnsLeadingZeros.RunTest();
Test_F_TimeAsString_ms_ReturnsTimeString_ms.RunTest();
Test_F_TimestampAsFilenameString_ReturnsFilenameString.RunTest();
Test_TStringSplitter_Handles_Empty_String.RunTest();
Test_TStringSplitter_ReturnsRemainder.RunTest();
Test_TStringSplitter_Splits_On_Tab.RunTest();
Test_TStringSplitter_Handles_Empty_SubString.RunTest();
Test_TStringSplitter_Handles_Multiple_Empty_SubStrings.RunTest();
Test_F_PadString_PadsShortStrings.RunTest();
Test_F_PadString_TruncsLongString.RunTest();
Test_F_TimestampAsFilename_ms.RunTest();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>