<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_ValueChanged" Id="{fbb70e0f-dba0-4bb1-abc5-028b84aa94a5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ValueChanged
VAR_INPUT
    Value : INT;
END_VAR
VAR_OUTPUT
    Changed : BOOL;
END_VAR
VAR
    OldValue : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Changed := Value <> OldValue;
OldValue := Value;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>