<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="PB_TestRunner" Id="{3b63ae67-b72c-01c4-320e-55d8016b25a9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PB_TestRunner
VAR
    Test_DateAsString                        : Test_DateAsString;
    Test_DateTimeAsString                    : Test_DateTimeAsString;
    Test_DateTimeAsString_ms                 : Test_DateTimeAsString_ms;
    Test_TimeAsString_24HourFormat           : Test_TimeAsString_24HourFormat;
    Test_TimeAsString_IncludesLeadingZeros   : Test_TimeAsString_IncludesLeadingZeros;
    Test_TimeAsString_ms                     : Test_TimeAsString_ms;
    Test_TimestampAsFilenameString           : Test_TimestampAsFilenameString;
    
    Test_StringSplitter_Handles_Empty_String : Test_StringSplitter_Handles_Empty_String;
    Test_StringSplitter_ReturnsRemainder     : Test_StringSplitter_ReturnsRemainder;
    Test_StringSplitter_Splits_On_Tab        : Test_StringSplitter_Splits_On_Tab;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[tcl_UnitTest.TestFramework.TestRunner();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>